/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JTable;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Fuentes <luisfuau10@gmail.com>
 */
public final class VistaInteractiva extends javax.swing.JFrame {

    private PreparedStatement ps;
    private ResultSet rs;
    private ConexionGeneral conexion;
    private Connection con;
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form Vista
     */
    public VistaInteractiva() {
        initComponents();
        this.setLocationRelativeTo(null);
        id_tf.setVisible(false);
        
        refresh();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        producto_jt = new javax.swing.JTable();
        codigo_tf = new javax.swing.JTextField();
        nombre_tf = new javax.swing.JTextField();
        precio_tf = new javax.swing.JTextField();
        cantidad_tf = new javax.swing.JTextField();
        eliminar_bt = new javax.swing.JButton();
        modificar_bt = new javax.swing.JButton();
        guardar_bt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        producto_jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        producto_jt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                producto_jtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(producto_jt);

        codigo_tf.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N

        nombre_tf.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N

        precio_tf.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N

        cantidad_tf.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N

        eliminar_bt.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N
        eliminar_bt.setText("Eliminar");
        eliminar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_btActionPerformed(evt);
            }
        });

        modificar_bt.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N
        modificar_bt.setText("Modificar");
        modificar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_btActionPerformed(evt);
            }
        });

        guardar_bt.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N
        guardar_bt.setText("Guardar");
        guardar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_btActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N
        jLabel4.setText("Cantidad:");

        jLabel3.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N
        jLabel3.setText("Precio:");

        jLabel2.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("ABeeZee", 0, 14)); // NOI18N
        jLabel5.setText("Codigo:");

        id_tf.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nombre_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(precio_tf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigo_tf)
                            .addComponent(cantidad_tf, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(id_tf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardar_bt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modificar_bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminar_bt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(codigo_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombre_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(precio_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cantidad_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardar_bt)
                            .addComponent(modificar_bt)
                            .addComponent(eliminar_bt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void producto_jtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_producto_jtMouseClicked
        acceder();
    }//GEN-LAST:event_producto_jtMouseClicked

    private void guardar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_btActionPerformed
        guardar();
    }//GEN-LAST:event_guardar_btActionPerformed

    private void modificar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_btActionPerformed
        modificar();
    }//GEN-LAST:event_modificar_btActionPerformed

    private void eliminar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_btActionPerformed
        eliminar();
    }//GEN-LAST:event_eliminar_btActionPerformed
    
    public void acceder()
    { 
        con=null;
        try
        {
            conexion = new ConexionGeneral("localhost", "3306", "tienda", "root", "1234");
            con = conexion.getConnection();
        
            int numFila = producto_jt.getSelectedRow();
            String codigo = producto_jt.getValueAt(numFila, 0).toString();
            String sql = "SELECT * FROM producto WHERE codigo=?";
            
            ps = con.prepareStatement(sql);
            ps.setString(1, codigo);
            rs = ps.executeQuery();
            
            while(rs.next())
            {
                codigo_tf.setText(rs.getString("codigo"));
                nombre_tf.setText(rs.getString("nombre"));
                precio_tf.setText(rs.getString("precio"));
                cantidad_tf.setText(rs.getString("cantidad"));
                id_tf.setText(rs.getString("id"));
            }
            
            con.close();
        }
        catch(SQLException ex)
        {
            System.err.println(ex.toString());
        }
        
    }
    
    public void guardar()
    {
        try
        {
            conexion = new ConexionGeneral("localhost", "3306", "tienda", "root", "1234");
            con = conexion.getConnection();
            
            ps = con.prepareStatement("INSERT INTO producto(codigo, nombre, precio, cantidad) VALUES (?,?,?,?)");
            
            ps.setString(1, codigo_tf.getText());
            ps.setString(2, nombre_tf.getText());
            ps.setString(3, precio_tf.getText());
            ps.setString(4, cantidad_tf.getText());
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Producto guardado");
            
            Object[] fila = new Object[4];
            fila[0] = codigo_tf.getText();
            fila[1] = nombre_tf.getText();
            fila[2] = precio_tf.getText();
            fila[3] = cantidad_tf.getText();
            
            modelo.addRow(fila);
            limpiar();
            
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Error al guardar producto");
            System.err.println(e);
        }
        
        
    }
    
    public void modificar()
    {
        int Fila = producto_jt.getSelectedRow();
        ps = null;
        
        try
        {
            conexion = new ConexionGeneral("localhost", "3306", "tienda", 
                                            "root", "1234");
            con = conexion.getConnection();
            
            ps = con.prepareStatement("UPDATE producto SET nombre=?, precio=?, "
                                    + "cantidad=?, codigo=? WHERE id=?");
            
            ps.setString(1, nombre_tf.getText());
            ps.setString(2, precio_tf.getText());
            ps.setString(3, cantidad_tf.getText());
            ps.setString(4, codigo_tf.getText());
            ps.setString(5, id_tf.getText());
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Producto modificado");
            
            producto_jt.setValueAt(codigo_tf.getText(), Fila, 0);
            producto_jt.setValueAt(nombre_tf.getText(), Fila, 1);
            producto_jt.setValueAt(precio_tf.getText(), Fila, 2);
            producto_jt.setValueAt(cantidad_tf.getText(), Fila, 3);

            limpiar();
            
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Error al guardar producto");
            System.err.println(e);
        }
    }
    
    public void eliminar()
    {
        try
        {
            
            conexion = new ConexionGeneral("localhost", "3306", "tienda", "root", "1234");
            con = conexion.getConnection();
            
            int Fila = producto_jt.getSelectedRow();
            String codigo = producto_jt.getValueAt(Fila, 0).toString();
            
            ps = con.prepareStatement("DELETE FROM producto WHERE codigo=?");
            ps.setString(1, codigo);
            ps.execute();
            
            modelo.removeRow(Fila);
            limpiar();
            
        }catch(SQLException e)
        {
            System.out.println(e.toString());
        }
    }
    
    public void refresh()
    {
        try
        {
            
            producto_jt.setModel(modelo);
            
            conexion = new ConexionGeneral("localhost", "3306", "tienda", "root", "1234");
            con = conexion.getConnection();
        
            String sql = "SELECT codigo, nombre, precio, cantidad FROM producto";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("Código");
            modelo.addColumn("Nombre");
            modelo.addColumn("Precio");
            modelo.addColumn("Cantidad");
            
            int[] ancho = {50, 100, 50, 50};
            
            for(int x=0; x<cantidadColumnas; x++)
            {
                producto_jt.getColumnModel().getColumn(x).setPreferredWidth(ancho[x]);
            }
            
            while(rs.next())
            {
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i=0; i<cantidadColumnas; i++)
                {
                    filas[i] = rs.getObject(i + 1);
                }
                
                modelo.addRow(filas);
            }
         
            con.close();
        }
        catch(SQLException ex)
        {
            System.err.println(ex.toString());
        }
    }
    
    public void limpiar()
    {
        codigo_tf.setText(null);
        nombre_tf.setText(null);
        precio_tf.setText(null);
        cantidad_tf.setText(null);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInteractiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInteractiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInteractiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInteractiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VistaInteractiva().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cantidad_tf;
    public javax.swing.JTextField codigo_tf;
    public javax.swing.JButton eliminar_bt;
    public javax.swing.JButton guardar_bt;
    private javax.swing.JTextField id_tf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton modificar_bt;
    public javax.swing.JTextField nombre_tf;
    public javax.swing.JTextField precio_tf;
    private javax.swing.JTable producto_jt;
    // End of variables declaration//GEN-END:variables
}
