/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ComboBox;

import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author Luis Fuentes <luisfuau10@gmail.com>
 */
public class ComboBox extends javax.swing.JFrame {

    /**
     * Creates new form ComboBox
     */
    public ComboBox() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Estado vista = new Estado();
        DefaultComboBoxModel modeloEstados = new DefaultComboBoxModel(vista.mostrarEstados());
        estados_cb.setModel(modeloEstados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        estados_cb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        municipios_cb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        localidades_cb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos_ta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Estado:");

        estados_cb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        estados_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estados_cbItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Municipio:");

        municipios_cb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        municipios_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                municipios_cbItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Localidades:");

        localidades_cb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        localidades_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                localidades_cbItemStateChanged(evt);
            }
        });

        datos_ta.setColumns(20);
        datos_ta.setFont(new java.awt.Font("ABeeZee", 0, 13)); // NOI18N
        datos_ta.setRows(5);
        jScrollPane1.setViewportView(datos_ta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(municipios_cb, 0, 242, Short.MAX_VALUE)
                            .addComponent(estados_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(localidades_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(estados_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(municipios_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidades_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estados_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estados_cbItemStateChanged
        
        datos_ta.setText(null);
        
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            Estado estados = (Estado) estados_cb.getSelectedItem();
            Municipio municipios = new Municipio();
            DefaultComboBoxModel modeloMunicipios = new DefaultComboBoxModel(municipios.mostrarMunicipios(estados.getId()));
            
            municipios_cb.setModel(modeloMunicipios);
            localidades_cb.removeAllItems();
            
        }
    }//GEN-LAST:event_estados_cbItemStateChanged

    private void localidades_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_localidades_cbItemStateChanged
        
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            Estado estados = (Estado) estados_cb.getSelectedItem();
            Localidad localidades = (Localidad) localidades_cb.getSelectedItem();
            Municipio municipios = (Municipio) municipios_cb.getSelectedItem();
            
            datos_ta.setText("Estados: "+estados.getNombre() 
                         + "\nMunicipio: "+municipios.getNombre() 
                         + "\nLocalidad: " + localidades.getNombre());
            
        }
        
    }//GEN-LAST:event_localidades_cbItemStateChanged

    private void municipios_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_municipios_cbItemStateChanged
        
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            
            Municipio municipios = (Municipio) municipios_cb.getSelectedItem();
            Localidad localidades = new Localidad();
            DefaultComboBoxModel modeloLocalidades = new DefaultComboBoxModel(localidades.mostrarLocalidades(municipios.getId()));
            
            localidades_cb.setModel(modeloLocalidades);
            
        }
        
    }//GEN-LAST:event_municipios_cbItemStateChanged

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea datos_ta;
    private javax.swing.JComboBox<String> estados_cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> localidades_cb;
    private javax.swing.JComboBox<String> municipios_cb;
    // End of variables declaration//GEN-END:variables
}
