/*
    El objetivo de este programa es poder crear una conexión entre la aplicación
    java y la basa de datos (MySQL Workbench), con el objeto de manipular datos.
*/

package Acceso;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Luis Fuentes
 */
public class acceder extends javax.swing.JFrame {

    private static Connection con; //Variable tipo Connection. 
    //Contantes String que guardará la url de la base de datos.
    public static final String URL = "jdbc:mysql://localhost:3306/escuela"
                                   + "?useTimezone=true&serverTimezone=UTC";
    public static final String USERNAME = "root"; //Constante para guardar el usuario del servidor
    public static final String PASSWORD = "4321"; //Contante para guarda la contraseña del servidor
    
    public acceder() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conectar_button = new javax.swing.JButton();
        desconectar_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conectar_button.setFont(new java.awt.Font("ABeeZee", 0, 18)); // NOI18N
        conectar_button.setText("Conectar");
        conectar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectar_buttonActionPerformed(evt);
            }
        });

        desconectar_button.setFont(new java.awt.Font("ABeeZee", 0, 18)); // NOI18N
        desconectar_button.setText("Desconectar");
        desconectar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desconectar_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desconectar_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(conectar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(conectar_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desconectar_button)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conectar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectar_buttonActionPerformed
        try{
            
            con = null; //Definir nulo la variable
            con = getConnection(); //Obtener lo que retorna getConnection();
            
            PreparedStatement ps; /*Variable PreparedStatement para poder enviar
            la instrucción al servidor por sql, para eliminar, crear, modificar 
            la base de datos*/
            ResultSet res;//Variable ResultSet trae los resultados de la consulta
            
            /*A ps se le asigna la conexión con la instrucción sql. La table de
            la base de datos se llama "persona", seleccionare de esa tabla*/
            ps = con.prepareStatement("SELECT * FROM persona");
            res = ps.executeQuery(); //ps se ejecuta con query.
            
            if(res.next()){//Si existen datos
                //Extraer nombre, apellido y teléfono de "persona".
                JOptionPane.showMessageDialog(null, res.getString("nombre") + " " +  
                                                    res.getString("apellido") + " " +
                                                    res.getString("telefono"));
            }else{
                JOptionPane.showMessageDialog(null, "No existen datos");
            }
            
            con.close();//Cerrar conexión
            res.close();//Cerrar el query.
            
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_conectar_buttonActionPerformed

    private void desconectar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desconectar_buttonActionPerformed
        con = null;
        
        if(con == null){
            JOptionPane.showMessageDialog(null, "Conexión terminada");
        }
    }//GEN-LAST:event_desconectar_buttonActionPerformed

    //Este método nos retorna la conexión a la base de datos
    public static Connection getConnection(){
        con = null; //con asignarle null
        
        try{
            
            Class.forName("java.sql.Driver"); //Cargar el driver
            //Mandarle la url, el usuario y la contraseña a con por el driverManager 
            con = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            //Mensaje para notificar la conexión exitosa
            JOptionPane.showMessageDialog(null, "Conexión establecida");
            
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e); //Mensaje para imprimir algún error
        }
        
        return con; //Retornar con y toda la información de la dirección.
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acceder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acceder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acceder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acceder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new acceder().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conectar_button;
    private javax.swing.JButton desconectar_button;
    // End of variables declaration//GEN-END:variables
}
